#!/usr/bin/env bash
#
# serve.sh — launch the CCNA Training app and expose it to the phone/LAN.
#
# Runs the Flask static server (serving ./dist) on PORT, then refreshes the
# Windows->WSL port-proxy so the app is reachable at http://<windows-LAN-ip>:PORT.
# Port 8080 is taken by GNS3, so we default to 8090.
#
# Usage:
#   ./serve.sh              # build if needed, start server, set up proxy
#   ./serve.sh --build      # force a fresh `npm run build` first
#   ./serve.sh --no-proxy   # WSL/local only, skip the Windows proxy + UAC prompt
#   PORT=9090 ./serve.sh    # use a different port end-to-end
#
set -euo pipefail
cd "$(dirname "$0")"

PORT="${PORT:-8090}"
LAN_IP="192.168.1.191"          # Windows LAN IP the phone uses (see README 4.1)
DO_BUILD=0
DO_PROXY=1
for arg in "$@"; do
  case "$arg" in
    --build)    DO_BUILD=1 ;;
    --no-proxy) DO_PROXY=0 ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

WSL_IP="$(hostname -I | awk '{print $1}')"
echo "==> WSL IP: $WSL_IP   port: $PORT"

# 1. Build the bundle if it's missing or --build was passed.
if [[ "$DO_BUILD" == 1 || ! -f dist/index.html ]]; then
  echo "==> Building (npm run build)..."
  npm run build
fi

# 2. (Re)start the Flask server on PORT, detached, no debug reloader.
echo "==> Starting server on 0.0.0.0:$PORT ..."
fuser -k "${PORT}/tcp" 2>/dev/null || true
setsid nohup python3 -c \
  "import server; server.app.run(host='0.0.0.0', port=${PORT}, debug=False, use_reloader=False)" \
  >/tmp/ccna_server_${PORT}.log 2>&1 < /dev/null &
disown 2>/dev/null || true

# Wait until it actually answers, and confirm it's OUR app (not GNS3 on a reused port).
echo -n "==> Waiting for server"
for _ in $(seq 1 15); do
  if curl -s --max-time 2 "http://127.0.0.1:${PORT}/" | grep -qi "CCNA Training"; then
    echo " — up."; break
  fi
  echo -n "."; sleep 1 2>/dev/null || true
done
if ! curl -s --max-time 3 "http://127.0.0.1:${PORT}/" | grep -qi "CCNA Training"; then
  echo
  echo "!! Server did not serve the CCNA app on ${PORT}. Last log lines:" >&2
  tail -n 15 "/tmp/ccna_server_${PORT}.log" >&2 || true
  exit 1
fi

# 3. Refresh the Windows->WSL port-proxy (IP changes across WSL restarts).
if [[ "$DO_PROXY" == 1 ]]; then
  PS_PATH="/mnt/c/Users/Public/wslproxy${PORT}.ps1"
  WIN_PS_PATH="C:\\Users\\Public\\wslproxy${PORT}.ps1"
  echo "==> Writing proxy script $PS_PATH (WSL IP baked in: $WSL_IP)"
  cat > "$PS_PATH" <<EOF
# Auto-generated by serve.sh — forwards Windows 0.0.0.0:${PORT} -> WSL ${WSL_IP}:${PORT}.
\$ErrorActionPreference = 'Stop'
\$log  = 'C:\\Users\\Public\\wslproxy.log'
\$Port = ${PORT}
\$wsl  = '${WSL_IP}'
try {
  cmd /c "netsh interface portproxy delete v4tov4 listenport=\$Port listenaddress=0.0.0.0" 2>\$null | Out-Null
  cmd /c "netsh interface portproxy add v4tov4 listenport=\$Port listenaddress=0.0.0.0 connectport=\$Port connectaddress=\$wsl" | Out-Null
  if (-not (Get-NetFirewallRule -DisplayName "WSL app \$Port" -ErrorAction SilentlyContinue)) {
    New-NetFirewallRule -DisplayName "WSL app \$Port" -Direction Inbound -LocalPort \$Port -Protocol TCP -Action Allow | Out-Null
  }
  "WSL_IP=\$wsl  PORT=\$Port" | Out-File \$log -Encoding ascii
  (netsh interface portproxy show v4tov4) | Out-File \$log -Append -Encoding ascii
  "=== OK ===" | Out-File \$log -Append -Encoding ascii
} catch { "ERROR: \$_" | Out-File \$log -Encoding ascii }
EOF
  echo "==> Running proxy elevated — APPROVE THE UAC PROMPT on the Windows screen."
  powershell.exe -Command \
    "Start-Process powershell -Verb RunAs -Wait -ArgumentList '-ExecutionPolicy','Bypass','-File','${WIN_PS_PATH}'" \
    2>/dev/null || true

  if powershell.exe -Command "netsh interface portproxy show v4tov4" 2>/dev/null | grep -q "${PORT} .* ${WSL_IP} "; then
    echo "==> Proxy active."
  else
    echo "!! Proxy mapping not confirmed — check C:\\Users\\Public\\wslproxy.log" >&2
  fi
fi

echo
echo "================================================================"
echo "  CCNA Training is running."
echo "    This PC:   http://127.0.0.1:${PORT}/"
[[ "$DO_PROXY" == 1 ]] && echo "    Phone/LAN: http://${LAN_IP}:${PORT}/   (same Wi-Fi)"
echo "  Stop the server later with:  fuser -k ${PORT}/tcp"
echo "================================================================"
